compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: YOUR_RANK
main_process_ip: YOUR_MAIN_HOST_IP
main_process_port: 9999
main_training_function: main
mixed_precision: bf16
num_machines: N_NODE
num_processes: N_GPU
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
