compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: config/deepspeed_config/stage2_offload.json
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_process_ip: YOUR_MAIN_HOST_IP
main_process_port: 9999
main_training_function: main
num_machines: N_NODE
num_processes: N_GPU
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
